// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqE-lAztoUxml07G1StpMpmeH545xeuk0',
    appId: '1:469179683240:web:d6862e4bb87974f0910d9d',
    messagingSenderId: '469179683240',
    projectId: 'camelvan',
    authDomain: 'camelvan.firebaseapp.com',
    storageBucket: 'camelvan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEGcE_s0INkhFQIOGowwumELO0kdw59Lc',
    appId: '1:469179683240:android:36e1635c77199329910d9d',
    messagingSenderId: '469179683240',
    projectId: 'camelvan',
    storageBucket: 'camelvan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJu8XCGohb1dwzGNv4tDVhfK1KUtJvBpc',
    appId: '1:469179683240:ios:62336dc1801286d7910d9d',
    messagingSenderId: '469179683240',
    projectId: 'camelvan',
    storageBucket: 'camelvan.appspot.com',
    iosClientId: '469179683240-ph65qtt3dl6qk8kf96dj26d59ceui6a6.apps.googleusercontent.com',
    iosBundleId: 'com.ctrlaltdefeat.camelvanFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJu8XCGohb1dwzGNv4tDVhfK1KUtJvBpc',
    appId: '1:469179683240:ios:cfa93a91d05e0db5910d9d',
    messagingSenderId: '469179683240',
    projectId: 'camelvan',
    storageBucket: 'camelvan.appspot.com',
    iosClientId: '469179683240-auiqctqb7cg7h69cnjmdhidlcndqgeir.apps.googleusercontent.com',
    iosBundleId: 'com.ctrlaltdefeat.camelvanFrontend.RunnerTests',
  );
}
